Repository cloudquery/filetypes, pull requests merged in 2023-06, with the labels that each got.

#172 fix(deps): Update module github.com/cloudquery/plugin-sdk/v3 to v3.8.1
  csv/testdata/TestWriteRead-default.csv
  csv/testdata/TestWriteRead-with_delimiter.csv
  csv/testdata/TestWriteRead-with_delimiter_headers.csv
  csv/testdata/TestWriteRead-with_headers.csv
  go.mod
  go.sum
  json/testdata/TestWriteRead.jsonl
  parquet/read.go
  parquet/write.go
  parquet/write_read_test.go
Labels: fix

#181 chore: Don't copy fields manually
  go.mod
  go.sum
  parquet/write.go
Labels: automerge, ignore-for-release

#190 fix(parquet): Simplify struct reading
  csv/read.go
  parquet/read.go
Labels: automerge, fix

#154 feat: Separate file parts
  client.go
  csv/write.go
  csv/write_read_test.go
  json/write.go
  json/write_read_test.go
  parquet/write.go
  parquet/write_read_test.go
  types/types.go
  write.go
Labels: automerge, feat

#203 fix: Use buffered writing mode in parquet
  parquet/write.go
  parquet/write_read_test.go
Labels: automerge, fix

#210 feat!: Upgrade to plugin-sdk v4
  client.go
  csv/read.go
  csv/write.go
  csv/write_read_test.go
  go.mod
  go.sum
  json/read.go
  json/write.go
  json/write_read_test.go
  parquet/read.go
  parquet/write.go
  parquet/write_read_test.go
  read.go
  spec.go
  spec_test.go
  stream.go
  stream_test.go
  types/types.go
  write.go
Labels: feat, breaking
