Repository cloudquery/filetypes, pull requests merged in 2023-01, with the labels that each got.

#25 fix(json): Panic when json is null
  json/transformer.go
Labels: fix

#30 feat: Include CSV headers
  csv/client.go
  csv/read.go
  csv/write.go
  csv/write_read_test.go
  json/client.go
  json/read.go
  json/write.go
  json/write_read_test.go
Labels: automerge, feat

#35 feat: Simplify Destinations
  client.go
  csv/spec.go
  go.mod
  go.sum
  json/spec.go
  read.go
  spec.go
  spec_test.go
  transformer.go
  write.go
Labels: feat

#39 chore(go): Refactor
  .gitignore
  client.go
  csv/transformer.go
  json/transformer.go
  spec.go
Labels: ignore-for-release

#44 feat: Change option name
  client.go
  csv/spec.go
  spec_test.go
Labels: automerge, feat

#48 fix: JSON Inetarray
  json/transformer.go
Labels: fix
