Repository cloudquery/filetypes, pull requests merged in 2025-07, with the labels that each got.

#648 chore: Fix tests
  csv/testdata/TestWriteRead-default.csv
  csv/testdata/TestWriteRead-with_delimiter.csv
  csv/testdata/TestWriteRead-with_delimiter_headers.csv
  csv/testdata/TestWriteRead-with_headers.csv
  go.mod
  go.sum
  json/testdata/TestWriteRead.jsonl
Labels: automerge, ignore-for-release

#652 fix: Parquet premature closing
  parquet/write.go
Labels: fix

#665 fix(deps): Update module github.com/cloudquery/plugin-sdk/v4 to v4.87.4
  csv/testdata/TestWriteRead-default.csv
  csv/testdata/TestWriteRead-with_delimiter.csv
  csv/testdata/TestWriteRead-with_delimiter_headers.csv
  csv/testdata/TestWriteRead-with_headers.csv
  go.mod
  go.sum
  json/testdata/TestWriteRead.jsonl
Labels: automerge, fix
